"use client";

import { motion } from "framer-motion";

import ScoreOverview from "./ScoreOverview";
import StrengthsCard from "./StrengthsCard";
import MissingSkillsCard from "./MissingSkillsCard";
import ImprovementsCard from "./ImprovementsCard";
import SummaryCard from "./SummaryCard";

interface ResumeReviewProps {
  analysis: {
    overallScore: number;
    atsScore: number;
    strengths: string[];
    weaknesses: string[];
    missingSkills: string[];
    improvements: string[];
    summary: string;
  };
}

export default function ResumeReview({
  analysis,
}: ResumeReviewProps) {
  return (
    <div className="mx-auto max-w-7xl space-y-8">

      {/* Hero */}
      <motion.div
        initial={{
          opacity: 0,
          y: -20,
        }}
        animate={{
          opacity: 1,
          y: 0,
        }}
        transition={{
          duration: 0.5,
        }}
        className="
          rounded-3xl
          border
          border-primary/10
          bg-gradient-to-r
          from-primary/10
          via-primary/5
          to-background
          p-8
        "
      >
        <div className="space-y-3">

          <div className="inline-flex items-center rounded-full bg-primary/10 px-4 py-1 text-sm font-medium text-primary">
            🤖 Generated by Saathi AI
          </div>

          <h1 className="text-4xl font-bold tracking-tight">
            AI Resume Review
          </h1>

          <p className="max-w-3xl text-muted-foreground leading-7">
            Your resume has been analyzed across ATS compatibility,
            technical skills, overall presentation, and industry
            expectations. Review the insights below to strengthen your
            profile and improve your opportunities.
          </p>

        </div>
      </motion.div>

      {/* Scores */}
      <ScoreOverview
        overallScore={analysis.overallScore}
        atsScore={analysis.atsScore}
      />

      {/* Main Grid */}
      <div className="grid gap-8 xl:grid-cols-2">

        <StrengthsCard
          strengths={analysis.strengths}
        />

        <MissingSkillsCard
          skills={analysis.missingSkills}
        />

      </div>

      <ImprovementsCard
        improvements={analysis.improvements}
      />

      <SummaryCard
        summary={analysis.summary}
      />

    </div>
  );
}