"use client";

import { Sparkles } from "lucide-react";
import SectionCard from "@/components/ui/SectionCard";

interface Props {
  summary: string;
}

const HIGHLIGHT_RULES = [
  {
    terms: ["strong", "solid", "excellent", "good", "foundation", "experience"],
    style: "bg-emerald-500/10 text-emerald-700 dark:text-emerald-300 border-emerald-500/20",
    dot: "🟢",
  },
  {
    terms: ["ats", "formatting", "measurable", "achievements", "improving", "competitiveness"],
    style: "bg-amber-500/10 text-amber-700 dark:text-amber-300 border-amber-500/20",
    dot: "🟡",
  },
  {
    terms: ["react", "next.js", "typescript", "docker", "cloud", "python", "node", "javascript", "supabase", "postgres", "git"],
    style: "bg-blue-500/10 text-blue-700 dark:text-blue-300 border-blue-500/20",
    dot: "🔵",
  },
];

function highlightText(text: string) {
  if (!text) return null;

  // Match words or key phrases
  const regex = /(\b(?:strong|solid|excellent|good|ATS|formatting|measurable|achievements|improving|competitiveness|React|Next\.js|TypeScript|Docker|Cloud|Python|Node|JavaScript|Supabase|Postgres|Git)\b)/gi;

  const parts = text.split(regex);

  return parts.map((part, index) => {
    const lower = part.toLowerCase();
    const rule = HIGHLIGHT_RULES.find((r) =>
      r.terms.some((t) => t === lower)
    );

    if (rule) {
      return (
        <span
          key={index}
          className={`inline-flex items-center gap-1 font-semibold px-2 py-0.5 rounded-md border text-xs mx-0.5 ${rule.style}`}
        >
          <span className="text-[10px]">{rule.dot}</span>
          <span>{part}</span>
        </span>
      );
    }

    return <span key={index}>{part}</span>;
  });
}

export default function SummaryCard({ summary }: Props) {
  return (
    <SectionCard
      title="AI Summary"
      subtitle="Overall assessment generated by Saathi AI"
      icon={<Sparkles className="h-5 w-5" />}
    >
      <div className="rounded-2xl border border-primary/10 bg-gradient-to-br from-primary/5 via-background to-background p-6">
        <p className="leading-8 text-foreground text-sm sm:text-base">
          {highlightText(summary)}
        </p>
      </div>
    </SectionCard>
  );
}